language: python
python:
  - "3.5"
  - "3.6"
#  - "3.7" Broken in travis https://github.com/travis-ci/travis-ci/issues/9815
  
# command to install dependencies
install:
  - python -m pip install -r requirements.txt
  - python -m pip install pytest-cov coveralls

# command to run tests
script:
  - python setup.py -apikey $api_key
  - python -m pytest Tests/ --cov=./ -v
after_success:
  - coveralls
